### ISSUE TITLE
Please Help.

### ISSUE THREAD

**Issue by iamrahatul** [Brolijah/YACpkTool#1]
Unhandled Exception: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at CriCpkMaker.CBinary.AnalyzeCpkFileSub(CFileData filedata, _criheap_struct* heap)
   at CriCpkMaker.CBinary.AnalyzeCpkFile(CFileData filedata, String fpath)
   at CriCpkMaker.CpkMaker.AnalyzeCpkFile(String fpath)
   at YACpkTool.Program.Main(String[] args)

This happens when I extract a cpk file.

**Comment by Brolijah** [comment]
Late reply... I'd need more context with this error. Further, I'm unsure if I could correct this since the error thrown is by the DLL. If you can (and still care), what was the exact path to your CPK you attempted to open?
